In [3]:
np.random.rand(10)


array([0.18105394, 0.61202939, 0.35606366, 0.31701514, 0.1929671 ,
       0.17401011, 0.13671283, 0.81546263, 0.11893434, 0.8290657 ])

In [4]:
np.random.randn(10)

array([ 0.90880603, -0.57786169,  0.58931242, -0.53012809, -0.40280411,
       -0.05274158, -1.30066753, -0.22042613,  0.36838537,  0.19031967])

In [5]:
np.random.randint(10,20,10)

array([19, 14, 11, 17, 13, 10, 17, 12, 19, 15], dtype=int32)

In [9]:
import numpy as np
arr= np.arange(11,21)
arr
arr[1:5]


array([12, 13, 14, 15])