In [16]:
np.random.rand(10)


array([0.24536556, 0.58348455, 0.42887966, 0.73912247, 0.57359691,
       0.7842903 , 0.82468591, 0.24481567, 0.19129856, 0.57106337])

In [17]:
np.random.randn(10)

array([ 0.078309  , -0.3845907 , -1.59507906, -0.27849631, -1.79603982,
       -1.12987253, -0.51734496, -0.59832136,  0.39417581, -0.39805158])

In [18]:
np.random.randint(10,20,10)

array([15, 19, 13, 12, 16, 12, 16, 18, 10, 12], dtype=int32)

In [19]:
import numpy as np
arr= np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
arr_sclice= arr[5::2]
arr_sclice

array([16, 18, 20])

In [22]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

print only [2,3
           7,8]
           

In [24]:
arr[0:2,1:3]



array([[2, 3],
       [7, 8]])

In [3]:
import numpy as np 
s= sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [10]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=(sudoku[i:i+3,j:j+3])
        print(n)
if np.sum(n) != 45:
            print("Not a valid Sudoku")
else:
            print("Valid Sudoku")


[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
Valid Sudoku


In [11]:
data= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])
data.shape

(5, 3)

In [14]:
np.mean(data[:,0])


np.float64(7.0)